# Generated by Django 5.0.3 

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('bed', 'bed'), ('chair', 'chair'), ('table', 'table')], default=0, max_length=20),
            preserve_default=False,
        ),
    ]
