# Generated by Django 5.0.3 on 2024-03-22 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Bed', 'Bed'), ('Sofa', 'Sofa'), ('Table', 'Table'), ('Living Room', 'Living Room'), ('Bed Room', 'Bed Room'), ('Dinning', 'Dinning')], max_length=20),
        ),
    ]
